print("python is a case sensitive langauge")
print("sky is pretty")
print("clouds look beeautiful")
print("python is a case sensitive langauge")
print("sky is pretty")
print("clouds look beeautiful")
